cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - cargo/
    - target/

stages:
  - build

.build_template: &build
  image: "rust:latest"
  stage: build
  before_script:
    - export PATH="/root/.cargo/bin:$PATH"
    - rustup target add $TARGET || true # Ignore failures when the target and toolchain are the same
    - cargo update
  script:
    - cargo build --examples --target=$TARGET
    - cargo build --tests --target=$TARGET
    - cargo test --target=$TARGET

x86_64-unknown-linux-gnu:
  <<: *build
  variables:
    TARGET: x86_64-unknown-linux-gnu

# WIP for these, don't work yet
# x86_64-unknown-freebsd:
#   <<: *build
#   variables:
#     TARGET: x86_64-unknown-freebsd

# x86_64-pc-windows-gnu:
#   <<: *build
#   variables:
#     TARGET: x86_64-pc-windows-gnu
