[package]
name = "human_bytes"
version = "0.2.1"
authors = ["Namkhai B. <namkhai.n3@protonmail.com>"]
edition = "2018"

description = "Crate to convert bytes into human-readable values"

repository = "https://gitlab.com/forkbomb9/human_bytes-rs"
readme = "README.md"
keywords = ["bytes", "conversion"]
license = "BSD-2-Clause"

[badges]
# GitLab CI
gitlab = { repository = "forkbomb9/human_bytes-rs"}

[features]
default = []

fast = [ "lexical" ]
bibytes = []

[dependencies]
lexical =  { version = "5.2", optional = true }
