[package]
name = "human_bytes"
version = "0.3.1"
authors = ["Namkhai B. <me@forkbomb9.ch>"]
edition = "2018"

description = "Crate to convert bytes into human-readable values"

repository = "https://sr.ht/~f9/human_bytes"
readme = "README.md"
keywords = ["bytes", "conversion", "format", "value-formatting", "utility"]
license = "BSD-2-Clause"

[features]
default = []
fast = [ "lexical" ]
bibytes = []

[dependencies]
lexical = { version = "6.0", optional = true }
