[package]
name = "human_bytes"
version = "0.3.0"
authors = ["Namkhai B. <me@forkbomb9.ch>"]
edition = "2018"

description = "Crate to convert bytes into human-readable values"

repository = "https://gitlab.com/forkbomb9/human_bytes-rs"
readme = "README.md"
keywords = ["bytes", "conversion", "format", "value-formatting", "utility"]
license = "BSD-2-Clause"

[badges]
# GitLab CI
gitlab = { repository = "forkbomb9/human_bytes-rs"}

[features]
default = []

fast = [ "lexical" ]
bibytes = []

[dependencies]
lexical =  { version = "5.2", optional = true }
